version: "2"
linters:
  enable:
    - copyloopvar
    - errname
    - gochecknoinits
    - importas
    - paralleltest
    - prealloc
    - testpackage
    - thelper
    - unconvert
    - unparam
  disable:
    - unused
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
